namespace AutoEditing.LlmEditor.Planning;

internal static class ProgressiveAssemblySchemas
{
	public const string Sketch = """
	{
	  "type":"object","additionalProperties":false,
	  "required":["schemaVersion","requestId","editorialThesis","sections","clipOrder","syncStrategy","reservations","uncertainties"],
	  "properties":{
	    "schemaVersion":{"type":"integer","const":1},
	    "requestId":{"type":"string","minLength":1},
	    "editorialThesis":{"type":"string","minLength":1},
	    "sections":{"type":"array","minItems":1,"items":{"type":"object","additionalProperties":false,
	      "required":["sectionId","regionId","editorialRole","energyDirection","pacingIntent","rationale"],
	      "properties":{
	        "sectionId":{"type":"string","minLength":1},"regionId":{"type":"string"},
	        "editorialRole":{"type":"string","minLength":1},"energyDirection":{"type":"string","minLength":1},
	        "pacingIntent":{"type":"string","minLength":1},"rationale":{"type":"string","minLength":1}
	      }}},
	    "clipOrder":{"type":"array","minItems":1,"items":{"type":"object","additionalProperties":false,
	      "required":["order","clip","sectionId","editorialRole","rationale","alternativeClipReferenceIds","confidence"],
	      "properties":{
	        "order":{"type":"integer","minimum":1},"clip":{"$ref":"#/$defs/clip"},
	        "sectionId":{"type":"string","minLength":1},"editorialRole":{"type":"string","minLength":1},
	        "rationale":{"type":"string","minLength":1},
	        "alternativeClipReferenceIds":{"type":"array","items":{"type":"string","minLength":1}},
	        "confidence":{"type":"number","minimum":0,"maximum":1}
	      }}},
	    "syncStrategy":{"type":"object","additionalProperties":false,
	      "required":["density","preferredMusicalTypes","rationale"],
	      "properties":{
	        "density":{"type":"string","minLength":1},
	        "preferredMusicalTypes":{"type":"array","items":{"type":"string","minLength":1}},
	        "rationale":{"type":"string","minLength":1}
	      }},
	    "reservations":{"type":"array","items":{"type":"object","additionalProperties":false,
	      "required":["reservationId","purpose","regionId","preferredClipReferenceIds"],
	      "properties":{
	        "reservationId":{"type":"string","minLength":1},"purpose":{"type":"string","minLength":1},
	        "regionId":{"type":"string"},"preferredClipReferenceIds":{"type":"array","items":{"type":"string","minLength":1}}
	      }}},
	    "uncertainties":{"type":"array","items":{"type":"object","additionalProperties":false,
	      "required":["uncertaintyId","description","resolutionSignal"],
	      "properties":{
	        "uncertaintyId":{"type":"string","minLength":1},"description":{"type":"string","minLength":1},
	        "resolutionSignal":{"type":"string","minLength":1}
	      }}}
	  },
	  "$defs":{"clip":{"type":"object","additionalProperties":false,
	    "required":["referenceId","mediaPath"],
	    "properties":{"referenceId":{"type":"string","minLength":1},"mediaPath":{"type":"string","minLength":1}}}}
	}
	""";

	public const string ClipStep = """
	{
	  "type":"object","additionalProperties":false,
	  "required":["schemaVersion","requestId","stepIndex","clip","sourceWindow","primarySync","additionalSyncs","rationale","alternatives","confidence"],
	  "properties":{
	    "schemaVersion":{"type":"integer","const":1},
	    "requestId":{"type":"string","minLength":1},
	    "stepIndex":{"type":"integer","minimum":1},
	    "clip":{"$ref":"#/$defs/clip"},
	    "sourceWindow":{"type":"object","additionalProperties":false,
	      "required":["startSeconds","endSeconds","constantSpeed","velocityCurve"],
	      "properties":{
	        "startSeconds":{"type":"number","minimum":0},
	        "endSeconds":{"type":"number","exclusiveMinimum":0},
	        "constantSpeed":{"type":"number","minimum":0.25,"maximum":4},
	        "velocityCurve":{"type":["array","null"],"minItems":2,"maxItems":7,
	          "items":{"type":"object","additionalProperties":false,
	            "required":["offsetSeconds","speed"],
	            "properties":{
	              "offsetSeconds":{"type":"number","minimum":0},
	              "speed":{"type":"number","minimum":0.25,"maximum":4}
	            }}}
	      }},
	    "primarySync":{"$ref":"#/$defs/sync"},
	    "additionalSyncs":{"type":"array","items":{"$ref":"#/$defs/sync"}},
	    "rationale":{"type":"string","minLength":1},
	    "alternatives":{"type":"array","items":{"type":"object","additionalProperties":false,
	      "required":["description","rejectedBecause"],
	      "properties":{
	        "description":{"type":"string","minLength":1},
	        "rejectedBecause":{"type":"string","minLength":1}
	      }}},
	    "confidence":{"type":"number","minimum":0,"maximum":1}
	  },
	  "$defs":{
	    "clip":{"type":"object","additionalProperties":false,
	      "required":["referenceId","mediaPath"],
	      "properties":{"referenceId":{"type":"string","minLength":1},"mediaPath":{"type":"string","minLength":1}}},
	    "sync":{"type":"object","additionalProperties":false,
	      "required":["musicEventId","killIndex"],
	      "properties":{"musicEventId":{"type":"string","minLength":1},"killIndex":{"type":"integer","minimum":0}}}
	  }
	}
	""";
}
