<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>AutoEditing.Domain</AssemblyName>
    <RootNamespace>Core.Domain</RootNamespace>
    <LangVersion>latest</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Audio\**\*.cs" />
    <Compile Include="Clip\**\*.cs" />
    <Compile Include="Configuration\**\*.cs" />
    <Compile Include="Editing\**\*.cs" />
    <Compile Include="Logging\**\*.cs" />
    <Compile Include="Planning\**\*.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio.Core" Version="2.2.1" />
    <PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
