<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>AutoEditing.AutomaticEditor</AssemblyName>
    <RootNamespace>Core.Domain.Editing</RootNamespace>
    <LangVersion>latest</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Planning\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\AutoEditing.Domain.csproj" />
  </ItemGroup>

</Project>
