<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>AutoEditing.Vegas</AssemblyName>
    <RootNamespace>Core.Scripts</RootNamespace>
    <LangVersion>latest</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Interaction\**\*.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Planning\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\AutoEditing.Domain.csproj" />
    <ProjectReference Include="..\Iteration.Contracts\AutoEditing.Iteration.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ScriptPortal.Vegas">
      <HintPath>$(ProgramFiles)\VEGAS\VEGAS Pro 20.0\ScriptPortal.Vegas.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
